---
-   hosts: servers
    vars_files:
        - vars.yml
    gather_facts: false
    become: true

    tasks:
        - name: Pull sources from the repository.
          git: repo={{project_repo}} dest={{project_root}} version={{branch}}
          notify:
            - restart web server

    handlers:
      - include : handlers.yml
